"""
Configuration package — centralised settings for the LOGIN pipeline.

Modules:
    paths     — directory and file paths
    camera    — camera hardware & capture settings
    models    — model URLs and architecture parameters
    defaults  — tunable thresholds and parameters
"""

from .paths import (
    ROOT_DIR, IMG_DIR, ENHANCED_DIR, MODEL_DIR, EMBEDDINGS_DIR,
    BLAZEFACE_MODEL_PATH, FACE_LANDMARKER_PATH, REALESRGAN_MODEL_PATH,
    GFPGAN_MODEL_PATH, OPENVINO_SR_MODEL_XML, OPENVINO_SR_MODEL_BIN,
    ARCFACE_MODEL_PATH, ARCFACE_ZIP_PATH, FACE_DB_PATH, FACE_FRAMES_DB_PATH,
    MESH_DB_PATH, HNSW_INDEX_PATH, HNSW_LABELS_PATH,
)
from .camera import (
    CAMERA_SOURCE, CAMERA_BACKEND, CAMERA_CODEC, CAMERA_WIDTH, CAMERA_HEIGHT,
    CAMERA_FPS, CAMERA_BUFFER_SIZE, DEFAULT_CAPTURE_FRAMES, DEFAULT_BUFFER_SIZE,
    CAMERA_WARMUP_SEC, CAPTURE_TIMEOUT_SEC,
    ENROLL_FRAMES, ENROLL_POSE_HOLD_SEC, ENROLL_POSE_YAW_THRESH,
    ENROLL_POSE_PITCH_THRESH, ENROLL_BLUR_THRESH,
)
from .models import (
    BLAZEFACE_MODEL_URL, FACE_LANDMARKER_URL, REALESRGAN_MODEL_URL,
    ARCFACE_MODEL_URL, SR_NUM_IN_CH, SR_NUM_OUT_CH, SR_NUM_FEAT, SR_NUM_CONV,
    SR_UPSCALE, SR_TILE_SIZE, SR_TILE_PAD, ARCFACE_INPUT_SIZE,
    ARCFACE_EMBEDDING_DIM, ARCFACE_ONNX_THREADS,
)
from .defaults import (
    MIN_DETECTION_CONFIDENCE, MIN_FACE_BBOX_PX, FACE_BBOX_PADDING, DETECTOR_BACKEND,
    CLAHE_CLIP_LIMIT, CLAHE_TILE_GRID,
    LOW_LIGHT_BRIGHTNESS_THRESHOLD, LOW_LIGHT_TARGET_BRIGHTNESS, LOW_LIGHT_MAX_GAMMA,
    DEFAULT_SR_BACKEND, RECOGNITION_THRESHOLD, MESH_WEIGHT, DUPLICATE_THRESHOLD,
    VERIFY_TOP_K, MAX_FACES,
    HNSW_SPACE, HNSW_EF_CONSTRUCTION, HNSW_M, HNSW_EF_SEARCH, HNSW_MAX_ELEMENTS,
    MESH_MIN_DETECTION_CONFIDENCE, MESH_MIN_TRACKING_CONFIDENCE,
    SPOOF_ENABLED, SPOOF_Z_RANGE_THRESHOLD, SPOOF_Z_STD_THRESHOLD,
    SPOOF_LBP_ENABLED, SPOOF_LBP_HIST_VARIANCE_THRESHOLD, SPOOF_LBP_HF_ENERGY_THRESHOLD,
    SPOOF_NOISE_KURTOSIS_THRESHOLD, SPOOF_BLOCK_GRAD_VAR_THRESHOLD,
    SPOOF_LOCAL_NOISE_VAR_THRESHOLD,
    LIVENESS_ENABLED, EAR_BLINK_THRESHOLD, BLINK_CONSEC_FRAMES, LIVENESS_TIMEOUT_SEC,
    DOWNLOAD_TIMEOUT_SEC, DOWNLOAD_CHUNK_SIZE,
)
from .validation import validate_config
